version: '3.8'

services:
  vite-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:4173"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
    command: ["npm", "run", "preview"]
